baseURL = "https://tomazinmasatrip.eu"
languageCode = "sl-si"
paginate = 6
summarylength = 10
title = "Tomaž in Maša trip | Travel Blog"
theme = "blogge-hugo-theme"

[menu]
  [[menu.main]]
    name = "Domov"
    url= ""
    weight= 1
  [[menu.main]]
    name = "O naju"
    url= "about"
    weight= 2
  [[menu.main]]
    name = "Kontakt"
    url= "contact"
    weight= 3

[params]
  summarylength = 80
  logo = "images/logo.svg"
  author = "Tomaž Starašinič"
  authorThumb = "images/author.jpg"
  authorAddress = "Zemelj, Metlika"
  authorPhone = "+33-257634 534"
  instaUsername = "tomazstarasinic"
  facebookUsername = "tomaz.starasinic"
  twitterUsername = "mary_astor"
  linkedinUsername = "mary_astor"
  author2 = "Maša Petan"
  author2Thumb = "images/author.png"
  author2Address = "Celje"
  author2Phone = "+33-257634 534"
  blogTitle = "Blog"
  blogSubTitle = "Preberite zadnji blog iz najinega potovanja"
  video = false
  videoBlogIcon = "images/blog/icon.svg"
  videoBlogsTitle = "Zadnji Videi"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  fabformURL  = "9AJk8ro"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"

[taxonomies]
  tag = "tags"
  category = "categories"
