baseURL = "https://tomazinmasatrip.eu"
languageCode = "sl-si"
paginate = 6
summarylength = 10
title = "Tomaž in Maša trip | Travel Blog"
theme = "blogge-hugo-theme"

[menu]
  [[menu.main]]
    name = "Domov"
    url= ""
    weight= 1
  [[menu.main]]
    name = "O naju"
    url= "about"
    weight= 2
  [[menu.main]]
    name = "Kontakt"
    url= "contact"
    weight= 3

[params]
  summarylength = 80
  logo = "images/logo.svg"
  author = "Tomaž Starašinič"
  authorThumb = "images/tomaz_in_medo.png"
  authorAddress = "Metlika, Slovenija"
  authorPhone = "+33-257634 534"
  authorMail = "tomaz.starasinic@hotmail.com"
  instaUsername = "tomazstarasinic"
  facebookUsername = "tomaz.starasinic"
  youTubeUsername = "@tomazs95"
  linkedinUsername = "mary_astor"
  masaAuthor = "Maša Petan"
  masaThumb = "images/masa_in_zaba.png"
  masaAddress = "Celje, Slovenija"
  masaPhone = "+33-257634 534"
  masaMail = "petan.masa@gmail.com"
  instaUsernameMasa = "masha_ptn"
  facebookUsernameMasa = "masa.petan"
  youTubeUsernameMasa = "@tomazs95"
  blogTitle = "Blog"
  blogSubTitle = "Kaj dogaja na poti."
  video = false
  videoBlogIcon = "images/blog/icon.svg"
  videoBlogsTitle = "Zadnji videi"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  fabformURL  = "9AJk8ro"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"

[taxonomies]
  tag = "tags"
