name: Tomaz in Masa trip deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1.
      - uses: actions/checkout@v3

      # 2.
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended: true

      # 3.
      - name: Clone theme
        run: git submodule update --init --recursive

      # 4.
      - name: Hugo build
        run: |
          cd $GITHUB_WORKSPACE
          hugo -v          

      # # 5.
      # - name: Rsync Deployments Action
      #   uses: Burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -avzr --delete
      #     path: public/
      #     remote_path: /home/tomazinm/public_html/
      #     remote_host: 152.89.234.190:21
      #     remote_user: tomazs
      #     remote_key: ${{ secrets.HUGODEPLOYACTION_SSH_KEY }}
      # 5.
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          local-dir: public/
          server-dir: /home/tomazinm/public_html/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp

